require:
  - rubocop-performance
  - rubocop-rails
# 1行の文字数に関する指摘
Layout/LineLength:
  Enabled: false
# スペースを複数入れるなという指摘
Layout/SpaceBeforeComma:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false
# マジックコメント必須の指摘
Style/FrozenStringLiteralComment:
  Enabled: false
# シンボルによる配列の%記法のチェック
Style/SymbolArray:
  Enabled: false
# classの前に説明文の追加必須
Style/Documentation:
  Enabled: false
# enumの記法チェック
Rails/EnumSyntax:
  Enabled: false
# i18nを使用していない日本語表記チェック
Rails/I18nLocaleTexts:
  Enabled: false
# メソッドの複雑さ/行数の許容範囲
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 8
# モジュールのネストした形式
Style/ClassAndModuleChildren:
  Enabled: false
AllCops:
  NewCops: enable
  # rubocopの対象外ファイル
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "config/environments/*"
    - "config/puma.rb"
    - "spec/**/*"