version: "3"
services:
  selenium:
    image: selenium/standalone-chromium:latest
    ports:
      - "4444:4444"
  db:
    image: postgres
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: "redis:latest"
    command: 
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - data_redis:/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - selenium
volumes:
  postgres_data:
  bundle_data:
  node_modules:
  data_redis:
