// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./controllers"
import "./plays/routines_plays"
import "./sortable"
import "./reset_btn"
import "./sort_routine"
import "./auto_complete_search"
import "./auto_complete_task"
import "./user_icon_preview"
import "./routine_edit_info_change"