name: RspecTest
on: push
jobs:
  rspec-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: "postgres"
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      selenium:
        image: "selenium/standalone-chrome"
        ports:
          - 4444:4444
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      
      - name: Cache Node
        uses: actions/cache@v4
        with:
          path: node_modules
          key:  node-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-${{ runner.os }}-
      
      - name: Yarn Install
        run: |
          yarn -v
          node -v
          yarn install

      - name: Bundler and Gem Install
        run: |
          gem install bundler -v '2.5.17'
          bundle install

      - name: Database Create
        run:  RAILS_ENV=test bundle exec rails db:create
      
      - name: Database Migration
        run:  RAILS_ENV=test bundle exec rails db:migrate
      
      - name: Database Seed
        run:  RAILS_ENV=test bundle exec rails db:seed

      - name: Build CSS
        run:  yarn build:css

      - name: Build Javascript
        run:  yarn build

      - name: Run Rspec
        run:  RAILS_ENV=test bundle exec rspec

